from PyQt5 import QtCore, QtGui, QtWidgets


class Html_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(1000, 750)
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(10, 70, 980, 670))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setFamily("微软雅黑")
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.save = QtWidgets.QPushButton(Dialog)
        self.save.setGeometry(QtCore.QRect(10, 10, 50, 50))
        self.save.setText("")
        self.save.setObjectName("save")
        self.save.setToolTip("保存")
        self.open = QtWidgets.QPushButton(Dialog)
        self.open.setGeometry(QtCore.QRect(70, 10, 50, 50))
        self.open.setText("")
        self.open.setObjectName("open")
        self.open.setToolTip("打开")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(130, 10, 600, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.see = QtWidgets.QPushButton(Dialog)
        self.see.setGeometry(QtCore.QRect(740, 10, 250, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.see.setFont(font)
        self.see.setObjectName("see")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "请输入保存的文件名"))
        self.see.setText(_translate("Dialog", "预览文本内容"))


class Code_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(1000, 750)
        self.save = QtWidgets.QPushButton(Dialog)
        self.save.setGeometry(QtCore.QRect(10, 10, 50, 50))
        self.save.setText("")
        self.save.setObjectName("save")
        self.open = QtWidgets.QPushButton(Dialog)
        self.open.setGeometry(QtCore.QRect(70, 10, 50, 50))
        self.open.setText("")
        self.open.setObjectName("open")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(130, 10, 860, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 70, 980, 670))
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.save.setToolTip(_translate("Dialog", "保存并运行"))
        self.open.setToolTip(_translate("Dialog", "打开"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "请输入保存的文件名"))


class Color_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(20, 250, 350, 30))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 90, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 170, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 210, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.red = QtWidgets.QSpinBox(Dialog)
        self.red.setGeometry(QtCore.QRect(130, 90, 250, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.red.setFont(font)
        self.red.setMaximum(255)
        self.red.setProperty("value", 220)
        self.red.setObjectName("red")
        self.blue = QtWidgets.QSpinBox(Dialog)
        self.blue.setGeometry(QtCore.QRect(130, 170, 250, 20))
        self.blue.setMaximum(255)
        self.blue.setProperty("value", 220)
        self.blue.setObjectName("blue")
        self.green = QtWidgets.QSpinBox(Dialog)
        self.green.setGeometry(QtCore.QRect(130, 130, 250, 20))
        self.green.setMaximum(255)
        self.green.setProperty("value", 220)
        self.green.setObjectName("green")
        self.choose_color = QtWidgets.QComboBox(Dialog)
        self.choose_color.setGeometry(QtCore.QRect(130, 210, 250, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.choose_color.setFont(font)
        self.choose_color.setObjectName("choose_color")
        self.choose_color.addItem("")
        self.choose_color.addItem("")
        self.choose_color.addItem("")
        self.choose_color.addItem("")
        self.choose_color.addItem("")
        self.choose_color.addItem("")
        self.show_color = QtWidgets.QLabel(Dialog)
        self.show_color.setGeometry(QtCore.QRect(20, 20, 360, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.show_color.setFont(font)
        self.show_color.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.show_color.setFrameShape(QtWidgets.QFrame.Panel)
        self.show_color.setFrameShadow(QtWidgets.QFrame.Plain)
        self.show_color.setLineWidth(3)
        self.show_color.setAlignment(QtCore.Qt.AlignCenter)
        self.show_color.setObjectName("show_color")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "红"))
        self.label_2.setText(_translate("Dialog", "绿"))
        self.label_3.setText(_translate("Dialog", "蓝"))
        self.label_4.setText(_translate("Dialog", "预设颜色"))
        self.choose_color.setItemText(0, _translate("Dialog", "淡灰色"))
        self.choose_color.setItemText(1, _translate("Dialog", "淡黄色"))
        self.choose_color.setItemText(2, _translate("Dialog", "浅红色"))
        self.choose_color.setItemText(3, _translate("Dialog", "淡蓝色"))
        self.choose_color.setItemText(4, _translate("Dialog", "浅绿色"))
        self.choose_color.setItemText(5, _translate("Dialog", "亮白色"))
        self.show_color.setText(_translate("Dialog", "颜色显示"))
